const pokemonData = {
        "scarlet-violet": [
        // New
        { "fileName": "Raid-Kommo-o", "info": "Kommo-o Raid Event (Shiny-Locked)", "categories": ["NEW", "RAIDS"] },
        { "fileName": "Gift (Marcos Iron Hands)", "info": "Marco's Iron Hands", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (WithSpecs Flutter Mane)", "info": "신여명's Flutter Mane", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (YOASOBI Pawmot)", "info": "YOASOBI Pawmot", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (Ray Yamanakas Amoonguss)", "info": "PJCS 2025 Ray Yamanaka's Amoonguss", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (Hyuma Flutter Mane)", "info": "PJCS 2025 Hyuma Hara's Flutter Mane", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (Wei Chyrs Rillaboom)", "info": "Wei Chyr's Rillaboom", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (Marcos Jumpluff)", "info": "Marco's Jumpluff", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (Wolfe Incineroar)", "info": "NAIC 2025 Wolfe's Incineroar", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (Town Ditto)", "info": "Pokémon Town - KOR Ditto Project", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift (PTC25 Porygon2)", "info": "PTC 2025 홍주영's Porygon2", "categories": ["NEW", "EVENTS"] },
        // Raids
        { "fileName": "Raid-Baxcalibur", "info": "Baxcalibur Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Porygon2", "info": "Porygon2 Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Garchomp", "info": "Garchomp Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Metagross", "info": "Metagross Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Salamence", "info": "Salamence Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Skeledirge", "info": "Skeledirge Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Quaquaval", "info": "Quaquaval Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Meowscarada", "info": "Meowscarada Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Rayquaza", "info": "Rayquaza Raid Event (Shiny)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Shiny-Brute Bonnet", "info": "Shiny Brute Bonnet 5 Star Raid Event", "categories": ["RAIDS"] },
        { "fileName": "Raid-Shiny-Flutter Mane", "info": "Shiny Flutter Mane 5 Star Raid Event", "categories": ["RAIDS"] },
        { "fileName": "Raid-Shiny-Iron Jugulis", "info": "Shiny Iron Jugulis 5 Star Raid Event", "categories": ["RAIDS"] },
        { "fileName": "Raid-Shiny-Iron Hands", "info": "Shiny Iron Hands 5 Star Raid Event", "categories": ["RAIDS"] },
        { "fileName": "Raid-Torterra", "info": "Torterra Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Feraligatr", "info": "Feraligatr Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Dondozo", "info": "Dondozo Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Delphox", "info": "Delphox Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Iron Bundle", "info": "Iron Bundle Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Infernape", "info": "Infernape Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Serperior", "info": "Serperior Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Incineroar", "info": "Incineroar Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Dragonite", "info": "Dragonite Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Sceptile", "info": "Sceptile Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Iron Leaves", "info": "Iron Leaves Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Walking Wake", "info": "Walking Wake Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Emboar", "info": "Emboar Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Swampert", "info": "Swampert Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Blaziken", "info": "Blaziken Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Primarina", "info": "Primarina Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Meganium", "info": "Meganium Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Empoleon", "info": "Empoleon Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Eevee", "info": "Eevee Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Typhlosion-Hisui", "info": "Typhlosion-Hisui Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Decidueye-Hisui", "info": "Decidueye-Hisui Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Mewtwo", "info": "Mewtwo Raid Event (Shiny Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Rillaboom", "info": "Rillaboom Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Gimmighoul-Chest", "info": "Gimmighoul-Chest Raid Event (Shiny)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Blastoise", "info": "Blastoise (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Venusaur", "info": "Venusaur (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Charizard", "info": "Charizard (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Cinderace", "info": "Cinderace (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Greninja", "info": "Greninja (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Decidueye", "info": "Decidueye Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Samurott-Hisui", "info": "Samurott-Hisui Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Samurott", "info": "Samurott Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Typhlosion", "info": "Typhlosion Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Inteleon", "info": "Inteleon Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Chesnaught", "info": "Chesnaught Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        { "fileName": "Raid-Pikachu", "info": "Pikachu Surf Raid Event (Shiny-Locked)", "categories": ["RAIDS"] },
        // Events
        { "fileName": "Gift Japan-Keldeo", "info": "Pokémon Mythical Pokémon Campaign", "categories": ["EVENTS"] },
        { "fileName": "Gift Japan-Zarude", "info": "Pokémon Mythical Pokémon Campaign", "categories": ["EVENTS"] },
        { "fileName": "Gift Japan-Deoxys", "info": "Pokémon Mythical Pokémon Campaign", "categories": ["EVENTS"] },
        { "fileName": "Gift LAIC Pelipper", "info": "Latin America International Championship", "categories": ["EVENTS"] },
        { "fileName": "Gift (Worlds24-Sylveon)", "info": "Pokemon Worlds24 Championships", "categories": ["EVENTS"] },
        { "fileName": "Gift (Worlds24-Steenee)", "info": "Pokemon Worlds24 Championships", "categories": ["EVENTS"] },
        { "fileName": "Gift (Roys-Fuecoco)", "info": "Roy's Fuecoco Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift (Dots-Quaxly)", "info": "Pokémon Horizons Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift (Nils-Porygon2)", "info": "Pokémon NA International Championship", "categories": ["EVENTS"] },
        { "fileName": "Gift (PJC-Talonflame)", "info": "Pokémon Japan Championships", "categories": ["EVENTS"] },
        { "fileName": "Gift (Coro-Iron Valiant)", "info": "CoroCoro Special Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift (Coro-Roaring Moon)", "info": "CoroCoro Special Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift (Darkrai)", "info": "Pokémon Indigo Disk Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift (Shiny Lucario)", "info": "Pokémon Indigo Disk Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift (Alex-Dragapult)", "info": "Alex's Dragapult", "categories": ["EVENTS"] },
        { "fileName": "Gift (Korea-Fidough)", "info": "Korea Bundle Fidough", "categories": ["EVENTS"] },
        { "fileName": "Gift Mew", "info": "Pokémon Presents Distribution MightyMark", "categories": ["EVENTS"] },
        { "fileName": "Gift (BDay-Charcadet)", "info": "Pokémon Center Birthday Charcadet", "categories": ["EVENTS"] },
        { "fileName": "Gift (BDay-Pawmi)", "info": "Pokémon Center Birthday Pawmi", "categories": ["EVENTS"] },
        { "fileName": "Gift (Munchlax)", "info": "Shiny Munchlax from DLC minigame", "categories": ["EVENTS"] },
        { "fileName": "Glaseado Cetitan", "info": "Pokémon: Paldean Wings Glaseado Cetitan", "categories": ["EVENTS"] },
        { "fileName": "Gift (PEIC-Palafin)", "info": "Gavin's PEIC Palafin", "categories": ["EVENTS"] },
        { "fileName": "Gift (PWC-Gastrodon)", "info": "Eduardo PWC Gastrodon", "categories": ["EVENTS"] },
        { "fileName": "Worlds23 Tatsugiri", "info": "Worlds23 Tatsugiri (Strechy)", "categories": ["EVENTS"] },
        { "fileName": "Gift (Nontaro-Grimmsnarl)", "info": "Nontaro's Shiny Grimmsnarl", "categories": ["EVENTS"] },
        { "fileName": "Gift (Paul-Arcanine)", "info": "Paul's Shiny Arcanine", "categories": ["EVENTS"] },
        { "fileName": "Gift (PreOrder Pikachu)", "info": "Pre-Order Flying Pikachu", "categories": ["EVENTS"] },
        { "fileName": "Gift (Lechonk)", "info": "Pokemon Event Lechonk", "categories": ["EVENTS"] },
        { "fileName": "1stChampSV", "info": "1st Champ Jiseok Garganacl", "categories": ["EVENTS"] },
        { "fileName": "GyaradosJF23", "info": "Jump Festa 2023 (Japan)", "categories": ["EVENTS"] },
        { "fileName": "Gift (Zoroark-Hisui)", "info": "DlC Purchase Hisui Zoroark", "categories": ["EVENTS"] },
        { "fileName": "Gift (Flabebe-Red)", "info": "Pokémon Center Birthday Red Flabébé", "categories": ["EVENTS"] },
        { "fileName": "Gift (Flabebe-Orange)", "info": "Pokémon Center Birthday Orange Flabébé", "categories": ["EVENTS"] },
        { "fileName": "Gift (Flabebe-Yellow)", "info": "Pokémon Center Birthday Yellow Flabébé", "categories": ["EVENTS"] },
        { "fileName": "Gift (Flabebe-Blue)", "info": "Pokémon Center Birthday Blue Flabébé", "categories": ["EVENTS"] },
        { "fileName": "Gift (Flabebe-White)", "info": "Pokémon Center Birthday White Flabébé", "categories": ["EVENTS"] },
        // Ditto
        { "fileName": "FreDitto", "info": "6IV Shiny French Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "EngDitto", "info": "6IV Shiny English Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "ItaDitto", "info": "6IV Shiny Italian Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "GerDitto", "info": "6IV Shiny German Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "EspDitto", "info": "6IV Shiny Spanish Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "JapDitto", "info": "6IV Shiny Japanese Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "FreDittoNoAS", "info": "0 Atk/Speed Shiny French Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "EngDittoNoAS", "info": "0 Atk/Speed Shiny English Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "JapDittoNoAS", "info": "0 Atk/Speed Shiny Japanese Breeding Ditto", "categories": ["DITTO"] },
        { "fileName": "Home Keldeo", "info": "Shiny Keldeo from Pokemon HOME", "categories": ["HOME"] },
        { "fileName": "Home Enamorus", "info": "Shiny Enamorus from Pokemon HOME", "categories": ["HOME"] },
        { "fileName": "Home Manaphy", "info": "Shiny Manaphy from Pokemon HOME", "categories": ["HOME"] },
        { "fileName": "Home Vivillon-Pokeball", "info": "Pokemon Center Online Distribution 2014", "categories": ["HOME"] },
        { "fileName": "Home Shiny Meloetta", "info": "Shiny Meloetta from Pokemon HOME", "categories": ["HOME"] },
        { "fileName": "Home Rayquaza-Galileo", "info": "Ancient Origins Distribution 2015 - ORAS", "categories": ["HOME"] },
        { "fileName": "Home Suicune-INV2011", "info": "Shiny Suicune INV 2011 Event", "categories": ["HOME"] },
        { "fileName": "Home Raikou-GAMESTP", "info": "Shiny Raikou Gamestop Giveaway 2011", "categories": ["HOME"] },
        { "fileName": "Home Dialga-SUM2013", "info": "Shiny Dialga SUM2013 Event", "categories": ["HOME"] },
        { "fileName": "Pogo (Roaming Gimmighoul)", "info": "Gimmighould Roaming form - POGO", "categories": ["HOME"] },
        { "fileName": "Home-Deoxys", "info": "Shiny Deoxys - PokeTransfer", "categories": ["HOME"] },
        { "fileName": "Home-Deoxys-Attack", "info": "Shiny Deoxys Attack form - PokeTransfer", "categories": ["HOME"] },
        { "fileName": "Home-Deoxys-Defense", "info": "Shiny Deoxys Defense form - PokeTransfer", "categories": ["HOME"] },
        { "fileName": "Home-Deoxys-Speed", "info": "Shiny Deoxys Speed form - PokeTransfer", "categories": ["HOME"] },
        { "fileName": "Home Eternatus", "info": "Shiny Distribution Eternatus", "categories": ["HOME"] },
        { "fileName": "Home Jirachi", "info": "Shiny Jirachi Pokemon Movie - SWSH", "categories": ["HOME"] },
        { "fileName": "POGO (Mew)", "info": "Shiny Pogo Mew", "categories": ["HOME"] },
        { "fileName": "Emerald (Mew)", "info": "Shiny Emerald Mew", "categories": ["HOME"] },
        { "fileName": "Home Zacian", "info": "Lancer Shiny Zacian", "categories": ["HOME"] },
        { "fileName": "Home Zamazenta", "info": "Arthur Shiny Zamazenta", "categories": ["HOME"] },
        { "fileName": "Home Zapdos-Galar", "info": "Wild Shiny Zapdos-Galar", "categories": ["HOME"] },
        { "fileName": "Home Articuno-Galar", "info": "Crown Shiny Articuno-Galar", "categories": ["HOME"] },
        { "fileName": "Home Moltres-Galar", "info": "Armor shiny Moltres-Galar", "categories": ["HOME"] },
        { "fileName": "Home Meloetta", "info": "Meloetta Worlds 18 Distribution", "categories": ["HOME"] },
        // EGGS
        { "fileName": "Egg (Phione)", "info": "Shiny Phione Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Grookey-M)", "info": "Shiny Male Grookey Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Grookey-F)", "info": "Shiny Female Grokkey Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Slowpoke-Galar-M)", "info": "Shiny Male Galar Slowpoke Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Slowpoke-Galar-F)", "info": "Shiny Galar Slowpoke Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Grimer-Alola-M)", "info": "Shiny Male Alola Grimer Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Grimer-Alola-F)", "info": "Shiny Female Alola Grimer Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Fennekin-F)", "info": "Shiny Female Fennekin Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Fennekin-M)", "info": "Shiny Male Fennekin Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Growlithe-Hisui-F)", "info": "Shiny Female Hisui Growlithe Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Growlithe-Hisui-M)", "info": "Shiny Male Hisui Growlithe Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Voltorb-Hisui)", "info": "Shiny Hisui Voltorb Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Chespin-F)", "info": "Shiny Female Chespin Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Chespin-M)", "info": "Shiny Male Chespin Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Sobble-M)", "info": "Shiny Male Sobble Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Sobble-F)", "info": "Shiny Female Sobble Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Klefki-M)", "info": "Shiny Male Klefki Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Klefki-F)", "info": "Shiny Female Klefki Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Oricorio-Baile)", "info": "Shiny Egg Oricorio-Baile Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Oricorio-Pau)", "info": "Shiny Egg Oricorio-Pau Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Oricorio-PomPom)", "info": "Shiny Egg Oricorio-PomPom Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Oricorio-Sensu)", "info": "Shiny Egg Oricorio-Sensu Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Cyndaquil-F)", "info": "Shiny Female Cyndaquil Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Cyndaquil-M)", "info": "Shiny Male Cyndaquil Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Oshawott-M)", "info": "Shiny Male Oshawott Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Oshawott-F)", "info": "Shiny Female Oshawott Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Rowlet-M)", "info": "Shiny Male Rowlet Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Rowlet-F)", "info": "Shiny Female Rowlet Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Zorua-Hisui-M)", "info": "Shiny Male Zorua Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Zorua-Hisui-F)", "info": "Shiny Female Zorua Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Froakie-F)", "info": "Shiny Female Froakie Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Froakie-M)", "info": "Shiny Male Froakie Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Charmander-M)", "info": "Shiny Male Charmander Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Charmander-F)", "info": "Shiny Female Charmander Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Charcadet-M)", "info": "Shiny Male Charcadet Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Charcadet-F)", "info": "Shiny Female Charcadet Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Frigibax-M)", "info": "Shiny Male Frigibax Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Frigibax-F)", "info": "Shiny Female Frigibax Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Fuecoco-M)", "info": "Shiny Male Fuecoco Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Fuecoco-F)", "info": "Shiny Female Fuecoco Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Toxel-F)", "info": "Shiny Female Toxel Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Toxel-M)", "info": "Shiny Male Toxel Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Dratini-F)", "info": "Shiny Female Dratini Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Dratini-M)", "info": "Shiny Male Dratini Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Sprigatito-M)", "info": "Shiny Male Sprigatito Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Sprigatito-F)", "info": "Shiny Female Sprigatito Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Quaxly-M)", "info": "Shiny Male Quaxly Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Quaxly-F)", "info": "Shiny Female Quaxly Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Mareanie-F)", "info": "Shiny Female Mareanie Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Mimikyu-F)", "info": "Shiny Female Mimikyu Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Wattrel-F)", "info": "Shiny Female Wattrel Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Cubchoo-F)", "info": "Shiny Female Cubchoo Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Cubchoo-M)", "info": "Shiny Male Cubchoo Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Rockruff-F)", "info": "Shiny Female Rockruff Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Rockruff-M)", "info": "Shiny Male Rockruff Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Toedscool-F)", "info": "Shiny Female Toadscool Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Toedscool-M)", "info": "Shiny Male Toadscool Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Scorbunny-M)", "info": "Shiny Male Scorbunny Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Scorbunny-F)", "info": "Shiny Female Scorbunny Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Wooper-Normal)", "info": "Shiny Normal Wooper Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Wooper-Paldea)", "info": "Shiny Paldea Wooper Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Meowth-Normal)", "info": "Shiny Meowth Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Meowth-Galar)", "info": "Shiny Meowth Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tauros-Combat)", "info": "Shiny Paldea Tauros Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tauros-Blaze)", "info": "Shiny Paldea Fire Tauros Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tauros-Water)", "info": "Shiny Paldea Water Tauros Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Combee-M)", "info": "Shiny Male Combee Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Combee-F)", "info": "Shiny Female Combee Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tatsugiri-Curly-F)", "info": "Shiny Female Curly Tatsugiri Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tatsugiri-Droopy-F)", "info": "Shiny Female Droopy Tatsugiri Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tatsugiri-Stretchy-F)", "info": "Shiny Female Stretchy Tatsugiri Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Nacli-M)", "info": "Shiny Male Nacli Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Houndour-M)", "info": "Shiny Male Houndour Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Klawf-F)", "info": "Shiny Male Klawf Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Gible-F)", "info": "Shiny Female Gible Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Fomantis-F)", "info": "Shiny Female Fomantis Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Fomantis-M)", "info": "Shiny Male Fomantis Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Ralts-F)", "info": "Shiny Female Ralts Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Ralts-M)", "info": "Shiny Male Ralts Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Riolu-F)", "info": "Shiny Female Riolu Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Riolu-M)", "info": "Shiny Male Riolu Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Axew)", "info": "Shiny Axew Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tinkatink)", "info": "Shiny Tinkatink Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tandemaus)", "info": "Shiny Tandemaus Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Pawmi)", "info": "Shiny Pawmi Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Zorua)", "info": "Shiny Zorua Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Mankey)", "info": "Shiny Mankey Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Applin)", "info": "Shiny Applin Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Bounsweet)", "info": "Shiny Bounsweet Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Cetoddle)", "info": "Shiny Cetoddle Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Deino)", "info": "Shiny Deino Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Drifloon)", "info": "Shiny Drifloon Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Flittle)", "info": "Shiny Flittle Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Capsakid)", "info": "Shiny Capsakid Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Cyclizar)", "info": "Shiny Cyclizar Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Dreepy)", "info": "Shiny Dreepy Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Finizen)", "info": "Shiny Finizen Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Lechonk)", "info": "Shiny Lechonkegg", "categories": ["EGGS"] },
        { "fileName": "Egg (Maschiff)", "info": "Shiny Maschiff egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Snom)", "info": "Shiny Snom Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tadbulb)", "info": "Shiny Tadbulb Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Sandygast)", "info": "Shiny Sandygast Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Smoliv)", "info": "Shiny Smoliv Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Luvdisc)", "info": "Shiny Luvdisc Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Larvesta)", "info": "Shiny Larvesta Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Rotom)", "info": "Shiny Rotom Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Mareep)", "info": "Shiny Mareep Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Happiny)", "info": "Shiny Happeny Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Tynamo)", "info": "Shiny Tynamo Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Scyther)", "info": "Shiny Scyther Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Sandile)", "info": "Shiny Sandile Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Shroomish)", "info": "Shiny Sahroomish Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Slowpoke)", "info": "Shiny Slowpoke Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Magikarp)", "info": "Shiny Magikarp Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Bruxish)", "info": "Shiny Bruxish Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Barboach)", "info": "Shiny Barboach Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Hatenna)", "info": "Shiny Hatenna Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Finneon)", "info": "Shiny Finneon Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Alomomola)", "info": "Shiny Alomomola Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Heracross)", "info": "Shiny Heracross Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Petilil)", "info": "Shiny Petilil Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Pichu-F)", "info": "Shiny Female Pichu Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Pichu-M)", "info": "Shiny Male Pichu Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Shinx-F)", "info": "Shiny Female Shinx Egg", "categories": ["EGGS"] },
        { "fileName": "Egg (Shinx-M)", "info": "Shiny Male Shinx Egg", "categories": ["EGGS"] }
    ],
    "sword-shield": [
        // New
        { "fileName": "Gift Zapdos-Galar", "info": "Pokémon International Challenge 2022", "categories": ["NEW", "EVENTS"] },
        { "fileName": "Gift Moltres-Galar", "info": "Pokémon International Challenge 2022", "categories": ["NEW","EVENTS"] },
        { "fileName": "Gift Articuno-Galar", "info": "Pokémon International Challenge 2022", "categories": ["NEW","EVENTS"] },
        { "fileName": "Gift Zacian", "info": "Pokémon - Gamestop Distribution", "categories": ["NEW","EVENTS"] },
        { "fileName": "Gift Zamazenta", "info": "Pokémon - Gamestop Distribution", "categories": ["NEW","EVENTS"] },
        { "fileName": "Gift Eternatus", "info": "Pokémon Scarlet & Violet Celebration", "categories": ["NEW","EVENTS"] },
        // Ditto
        { "fileName": "Breeding Ditto", "info": "Shiny Japan Breeding Ditto", "categories": ["DITTO"] },
        // Home
        { "fileName": "Home Shiny Keldeo", "info": "Shiny Keldeo from Pokemon HOME", "categories": ["HOME"] },
        { "fileName": "Home Shiny Diancie", "info": "Pokemon All-Stars Battle Gift", "categories": ["HOME"] },
        { "fileName": "Home VGC10 Eevee", "info": "Pokemon VGC10 Distribution", "categories": ["HOME"] },
        { "fileName": "Home Lance Dragonite", "info": "Pokemon ORAS Distribution (Lance's)", "categories": ["HOME"] },
        { "fileName": "Home Shiny Zygarde", "info": "USUM Pokémon Legendary Celebration Distribution", "categories": ["HOME"] },
        { "fileName": "Pogo (Mew)", "info": "Shiny POGO Mew", "categories": ["HOME"] },
        { "fileName": "Pogo (Meltan)", "info": "Shiny POGO Meltan", "categories": ["HOME"] },
        { "fileName": "Emerald (Mew)", "info": "Shiny Emerald Mew", "categories": ["HOME"] },
        { "fileName": "Home Zeraora", "info": "Distribution from via Pokemon HOME", "categories": ["HOME"] },
        // Events
        { "fileName": "Gift Shiny Grimmsnarl", "info": "Pokémon World Championships Festival", "categories": ["EVENTS"] },
        { "fileName": "Gift Zarude", "info": "Pokémon the Movie Secrets of the Jungle", "categories": ["EVENTS"] },
        { "fileName": "Gift Zarude-Dada", "info": "Pokémon the Movie Secrets of the Jungle", "categories": ["EVENTS"] },
        { "fileName": "Gift Shiny Celebi", "info": "Pokémon the Movie Secrets of the Jungle", "categories": ["EVENTS"] },
        { "fileName": "Gift Shiny Toxtricity-Amped", "info": "Pokémon Shining Fates Tie-In", "categories": ["EVENTS"] },
        { "fileName": "Gift Palkia", "info": "Pokémon Movie Fest Special Distribution -The Rise of Darkrai", "categories": ["EVENTS"] },
        { "fileName": "Gift Dialga", "info": "Pokémon Movie Fest Special Distribution -The Rise of Darkrai", "categories": ["EVENTS"] },
        { "fileName": "Gift Volcanion", "info": "Pokémon Mythical Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift Marshadow", "info": "Pokémon Mythical Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift Genesect", "info": "Pokémon Mythical Distribution", "categories": ["EVENTS"] },
        { "fileName": "Gift Ash-Gengar-Gmax", "info": "Pokémon Masters Eight Tournament", "categories": ["EVENTS"] },
        { "fileName": "Gift Ash-Dracovish", "info": "Pokémon Masters Eight Tournament", "categories": ["EVENTS"] },
        { "fileName": "Gift Ash-Dragonite", "info": "Pokémon Masters Eight Tournament", "categories": ["EVENTS"] },
        { "fileName": "Gift Ash-Lucario", "info": "Pokémon Masters Eight Tournament", "categories": ["EVENTS"] },
        { "fileName": "Gift Ash-Sirfetchd", "info": "Pokémon Masters Eight Tournament", "categories": ["EVENTS"] },
        { "fileName": "Gift Victini", "info": "Pokémon World Championships Livestream Distribution", "categories": ["EVENTS"] }
    ],
    "legends-arceus": [
        // Home
        { "fileName": "Home Enamorus", "info": "Shiny Enamorus from Pokemon HOME", "categories": ["HOME"] },
        { "fileName": "Home Manaphy", "info": "Shiny Manaphy from Pokemon HOME", "categories": ["HOME"] }
    ],
    "brilliant-diamond-shining-pearl": [
        // Data for this game will be added here
    ]
};